name = "SatelliteGeometryCalculations"
uuid = "a6f97a21-93c4-462f-b59c-cf4b526cfc64"
authors = ["Daniel Talavera Jim√©nez"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BasicInterpolators = "26cce99e-4866-4b6d-ab74-862489e035e0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
FiniteMesh = "d3ebd857-6980-4843-ad12-8da20c4645b4"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MTH229 = "ebaf19f5-aa55-568f-9bb2-d6722dad893b"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxAtmosphericModels = "5718ef0a-a30f-426d-bcd9-4cf31dd12909"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TickTock = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
UpdateJulia = "770da0de-323d-4d28-9202-0e205c1e0aff"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
